### PR TITLE
Add a flash abstraction layer

### PR DESCRIPTION
**Pull request by meklort**
This commit adds a flash abstraction layer enabling multiple backing stores to be used.
This change is a precursor to enabling file-based pnor devices and enabled multiple backing stores to be used without recompiling a binary.
When VIRTUAL_PNOR is enabled, the backing store defaults to the vpnor device unless valid mtd device is specified. This is to maintain compatibility with the previous implementation.

Signed-off-by: Evan Lojewski <github@meklort.com>

### CODE REVIEW

**Comment by meklort** [comment]
Please note that there has been minimal testing with VPNOR enabled. When enabled, the code is able to compile and can still use /dev/mtd* if specified.
I do not have a vpnor system setup, and so cannot test that vpnor still works.

Please let me know what changes / improvements you'd like.
Once this is merged, I will update the file-based pnor backing support to work with these changes.
Finally, once file-based pnor is enabled, work can be done to enable on-the-fly switching from one backing store to another via mboxctl.

**Comment by meklort** [comment]
Sounds good. There are some things that I don'r like with the changes as is, so I may still make some modifications, but please do suggest any changes / improvements.

- I'm not sure about the flash_hal data structure having things like the lpc reset + protocol version code in it, since those aren't directly related to the flash.
- It may make sense to make a mtd folder for the mtd specific code like the vpnor code (then adding a file backing folder in the next pull request)
- I currently have the flash_hal structure inside of mctx instead of as a pointer as it makes things slightly more efficient, it may be better to have a separate structure for each backing store and just update one pointer.
- It likely makes sense to add some additional error checking to make sure all entries in the flash hal are populated before using them.

Let me know what you think about the above / other options.

**Comment by amboar** [comment]
You've pretty much covered my concerns with your bullet points.

> I'm not sure about the flash_hal data structure having things like the lpc reset + protocol version code in it, since those aren't directly related to the flash.

Agreed, these should be separate.

> It may make sense to make a mtd folder for the mtd specific code like the vpnor code (then adding a file backing folder in the next pull request)

Yeah, I haven't thought about this enough yet. We'll see how it plays out.

> I currently have the flash_hal structure inside of mctx instead of as a pointer as it makes things slightly more efficient, it may be better to have a separate structure for each backing store and just update one pointer.

I feel that just updating the one pointer is a lot neater, and that the performance penalty taken isn't going to be significant in the overall scheme of things. Lets do that please.

Also I'm hesitant to have the struct named 'flash_hal', as the 'h' in 'hal' is going to become incorrect when we have the file-based backend. How about "data_source" or "backend"?

> It likely makes sense to add some additional error checking to make sure all entries in the flash hal are populated before using them.

Lets just `assert()` it, that way it gets out of the road in releases. The test cases should cover the setup.

**Comment by amboar** [comment]
So I've had a bit more of a think about the issue with `protocol_negotiate_version()`. We had different implementations for the mtd and vpnor backends so the vpnor backend could hijack `.create_window` of `struct protocol_ops`. Really this was done so the parameters of the request could be validated and an error could be returned if necessary in the case of the vpnor backend.

The history of this is that up until recently there was only one transport (the mailbox), two protocol implementations (v1 and v2) and one backend (mtd). Then the second backend, the virtual pnor, was introduced, which required the validation. As there were now two backends and two protocol implementations the place of least effort to override the `create_window()` behaviour was in the transport  (mailbox) interface as it was the one remaining choke-point.

Recently the DBus transport was introduced which removed the choke-point that was previously present, and we need consistent behaviour between the mailbox and DBus interfaces, so the dumb choice was to simply push the hijacking down a layer, to be done on protocol level.

Reflecting now on all of this, we never had the right solution. With your work in the pull request here I think it's become a bit clearer to me that we need a `.validate` function member of what is currently `struct flash_hal`. By doing that, we shift the code that's currently in the vpnor `create_window()` implementation to where it really belongs, which is in the backend. Implementations of `create_window()` would look something like:

```
if (ctx->flash.validate) {
    rc = ctx->flash->validate(offset, size);
    if (rc < 0)
        return rc;
}
/* Setup the window according to parameters */
...
}
```
Currently for the mtd backend we could just set `validate` to NULL and implement it for vpnor, moving the vpnor's current validation checks out from `create_window()`, which should allow us to unify `create_window()` with the mtd backend's implementation. Further, v3 of the protocol describes a flash locking capability, which would perfectly fit the `validate()` concept - i.e. we check if the requested window intersects any locked flash blocks and return an error if so. The `create_window()` implementation would remain a general fit even under this requirement, as the details are buried in the `validate()` call on the backend.

Are you happy to rework the change along these lines?

**Comment by meklort** [comment]
Adding a validate function seems perfectly reasonable and like a good option. I've just been reworking to rename `flash_hal` to `backend`, and I'll push the changes once I'm done. After that I can update it to use a validate function to remove protocol negotiate.

**Comment by meklort** [comment]
I've update the code with a number of changes including the validate change.

Please take a look at it and let me know if any other changes are needed.

**Comment by amboar** [comment]
Great, trying to find time to look at this.

**Comment by amboar** [comment]
Okay, I think we're going to have to follow the OpenBMC process a bit more closely with this series. It's a bit more messing around. I've been trying to avoid it to avoid putting you off @meklort, however I pulled down your changes and ran into some build breakages locally. They also need a rebase against the tip of master to resolve some (trivial) merge conflicts.

The proper OpenBMC process is to push patches to our Gerrit instance:

https://gerrit.openbmc-project.xyz/

The process you'll need to follow is documented here:

https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#submitting-changes-via-gerrit-server

Note that you've already signed the CLA, so ignore that part.

**Comment by meklort** [comment]
OK, i prefer to use gerrit anyway, so not a problem.

**Comment by amboar** [comment]
@meklort sorry it's taking a long time to get these patches in, but your push to gerrit is still failing CI. Do you have time to clean that up? Alternatively I can pick up where you've left off.

**Comment by amboar** [comment]
Alright, I'll have a poke around when I've got a moment.

**Comment by meklort** [comment]
Pull request has been reviewed on gerrit and merged in with commits 
 f1e547c74563d59f60d918c6fa673bb8cee6e669 and a042978b03c91ca3a716e99f313ef5cda42820ba
Making as closed.

**Comment by amboar** [comment]
Thanks for persisting @meklort !

**Pull request closed without merging**
